apiVersion: v1
kind: Secret
metadata:
  name: mcp-aiops-backend-secret
  namespace: default
  labels:
    app.kubernetes.io/name: mcp-aiops-backend
    app.kubernetes.io/part-of: aiops-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://USER:PASSWORD@/core_db?sslmode=disable&host=192.168.100.23,10.30.4.11&port=5432,5432&target_session_attrs=read-write&connect_timeout=5"
  LLM_API_KEY: ""
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""
  SMTP_HOST: "smtp.example.com"
  SMTP_USERNAME: "sender@example.com"
  SMTP_PASSWORD: "replace-me"
  SMTP_FROM: "aiops@example.com"
  OPS_REPORT_EMAIL_RECIPIENTS: "ops@example.com"
  RCA_EMAIL_RECIPIENTS: "ops@example.com"
  RCA_SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/replace/me"
