apiVersion: v1
kind: Secret
metadata:
  name: mcp-aiops-backend-secret
  namespace: default
  labels:
    app.kubernetes.io/name: mcp-aiops-backend
    app.kubernetes.io/part-of: aiops-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://USER:PASSWORD@your-rds-endpoint.ap-northeast-2.rds.amazonaws.com:5432/kkpp"
  LLM_API_KEY: ""
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""
  SMTP_HOST: "smtp.example.com"
  SMTP_USERNAME: "sender@example.com"
  SMTP_PASSWORD: "replace-me"
  SMTP_FROM: "aiops@example.com"
  OPS_REPORT_EMAIL_RECIPIENTS: "ops@example.com"
  RCA_EMAIL_RECIPIENTS: "ops@example.com"
